version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: petclinic-postgres
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - petclinic-net

  app:
    image: alkaponees/spring-petclinic-devsecops:$BUILD_VERSION
    container_name: petclinic-app
    ports:
      - "8081:8080"
    env_file:
      - .app-env
    depends_on:
      - db
    networks:
      - petclinic-net


volumes:
  db_data:

networks:
  petclinic-net:
    driver: bridge