version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: petclinic-postgres
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    image: alkaponees/spring-petclinic:latest
    container_name: petclinic-app
    ports:
      - "8081:8081"
    env_file:
      - .app-env
    depends_on:
      - postgres

volumes:
  db_data:
