CREATE TABLE IF NOT EXISTS vets (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name  TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_vets_last_name ON vets (last_name);

CREATE TABLE IF NOT EXISTS specialties (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);
CREATE INDEX IF NOT EXISTS idx_specialties_name ON specialties (name);

CREATE TABLE IF NOT EXISTS vet_specialties (
  vet_id       INT NOT NULL REFERENCES vets (id) ON DELETE CASCADE,
  specialty_id INT NOT NULL REFERENCES specialties (id) ON DELETE CASCADE,
  UNIQUE (vet_id, specialty_id)
);

CREATE TABLE IF NOT EXISTS types (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);
CREATE INDEX IF NOT EXISTS idx_types_name ON types (name);

CREATE TABLE IF NOT EXISTS owners (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name  TEXT NOT NULL,
  address    TEXT NOT NULL,
  city       TEXT NOT NULL,
  telephone  TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_owners_last_name ON owners (last_name);

CREATE TABLE IF NOT EXISTS pets (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL,
  birth_date DATE NOT NULL,
  type_id    INT NOT NULL REFERENCES types (id),
  owner_id   INT REFERENCES owners (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_pets_name ON pets (name);
CREATE INDEX IF NOT EXISTS idx_pets_owner_id ON pets (owner_id);

CREATE TABLE IF NOT EXISTS visits (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id      INT REFERENCES pets (id) ON DELETE CASCADE,
  visit_date  DATE NOT NULL,
  description TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_visits_pet_id ON visits (pet_id);
